name: sealed_unions
description: Sealed Unions for Dart
version: 3.0.2
maintainer: Android Alliance (@droidalliance)
authors: 
- Flutter Community <flutter-community@googlegroups.com>
- Android Alliance <contact+gh@androidalliance.co.uk>
homepage: https://github.com/fluttercommunity/dart_sealed_unions
documentation:
environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: "^1.3.3"
